name: Compile cv

on: push

jobs:
  compile_cv:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout-cv
        uses: actions/checkout@v3
        with:
          repository: epignatelli/cv
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile-to-html
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=cv.html main.tex

      - name: Checkout-epignatelli.github.io
        uses: actions/checkout@v3
        with:
          path: epignatelli.github.io

      - name: Push-results
        run: |
          mv -f cv.html epignatelli.github.io/_includes/cv.html
          cd epignatelli.github.io
          ls -la
          echo '{% include head.html %}'
          git config --global user.name 'Eduardo'
          git config --global user.email 'edu.pignatelli@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git pull
          git add _includes/cv.html
          git commit -m "bot publishes cv"
          git push
