name: Compile cv

on: push

jobs:
  compile_cv:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout-cv
        uses: actions/checkout@v3
        with:
          repository: epignatelli/cv
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile-to-html
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=cv.html main.tex

      - name: Checkout-epignatelli.github.io
        uses: actions/checkout@v3
        with:
          path: epignatelli.github.io

      - name: Rearrange
        run: mv -f cv.html epignatelli.github.io/cv.html

      - name: Push-results
        run: |
          cd epignatelli.github.io
          cat _includes/head.html cv.html > temp && mv temp cv.html
          git config --global user.name 'Eduardo'
          git config --global user.email 'edu.pignatelli@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git status -vv
          git fetch
          git pull
          git add cv.html
          git commit -am "bot publishes cv"
          git push
