name: Compile cv

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout-cv
        uses: actions/checkout@v3
        with:
          repository: epignatelli/cv
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile-to-html
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=cv.html main.tex

      - name: Checkout-main
        uses: actions/checkout@v3
        with:
          path: main

      - name: Print
        run: ls -lr -d "$PWD"/*

      - name: Rearrange
        run: \cp -r  cv.html _layouts/cv.html

      - name: Push-results
        run: |
          git config --global user.name 'Eduardo'
          git config --global user.email 'edu.pignatelli@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git pull
          git add cv.html
          git commit -am "Automated cv generation"
          git push
