name: Compile cv

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout-main
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout-cv
        uses: actions/checkout@v3
        with:
          repository: epignatelli/cv
          path: cv

      - run: ls -l

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=_layouts/cv.html main.tex

      - uses: actions/upload-artifact@master
        with:
          name: _layouts/cv.html
          path: _layouts/cv.html
