name: Compile cv

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout-main
        uses: actions/checkout@v3

      - name: Checkout-cv
        uses: actions/checkout@v3
        with:
          repository: epignatelli/cv
          token: ${{ secrets.GITHUB_TOKEN }}
          # path: cv

      - run: ls -l

      - run: cd cv

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=cv.html main.tex

      - uses: actions/upload-artifact@master
        with:
          name: cv.html
          path: epignatelli.github.io/_layouts/cv.html
